/**
 * TripTide — Enhanced Analytics API Routes (Phase 2)
 * 
 * API endpoints for the enhanced (cruise-specific) deal analysis and price forecast.
 * These endpoints serve data generated by the sync engine or on-demand via admin triggers.
 */

import { Router, Request, Response } from 'express';
import { getPool } from '../db/pool';
import {
  generateEnhancedDealAnalysis,
  generateEnhancedPriceForecast,
  batchGenerateEnhancedDealAnalyses,
  batchGenerateEnhancedPriceForecasts,
  isDealAnalysisStale,
  repairHeuristicOutput,
  type SailingContext,
  type CompetingSailingData,
} from '../services/enhancedAnalytics';
import { sanitizeDealAnalysisObject } from '../utils/contentFormatter';

const router = Router();

/* ====================================================================== */
/*  IN-MEMORY CACHE (60s TTL)                                              */
/* ====================================================================== */

interface CacheEntry<T> {
  data: T;
  generatedAt: number;
}

const ENHANCED_CACHE_TTL_MS = 60 * 1000; // 60 seconds
const dealCache = new Map<number, CacheEntry<any>>();
const forecastCache = new Map<number, CacheEntry<any>>();

function getCached<T>(cache: Map<number, CacheEntry<T>>, key: number): T | null {
  const entry = cache.get(key);
  if (entry && (Date.now() - entry.generatedAt) < ENHANCED_CACHE_TTL_MS) {
    return entry.data;
  }
  return null;
}

function setCached<T>(cache: Map<number, CacheEntry<T>>, key: number, data: T) {
  cache.set(key, { data, generatedAt: Date.now() });
}

/* ====================================================================== */
/*  HELPERS                                                                */
/* ====================================================================== */

async function buildSailingContext(sailingId: number, preferences?: { tripType?: string; cabinPriorities?: string[] }): Promise<SailingContext | null> {
  const pool = getPool();
  console.log('[BUILD_CONTEXT] Starting for sailing', sailingId);

  // Fetch sailing data
  const sailingResult = await pool.query(
    `SELECT id, cruise_line, ship_name, duration_days, departure_port,
            destination_region, departure_date, itinerary, cabin_categories, booking_url
     FROM sailings WHERE id = $1`,
    [sailingId]
  );

  if (sailingResult.rows.length === 0) return null;
  const s = sailingResult.rows[0];
  console.log('[BUILD_CONTEXT] Sailing fetched:', s.cruise_line, s.ship_name);

  // Fetch current pricing (latest snapshot per cabin)
  const pricingResult = await pool.query(
    `SELECT cabin_type, total_out_the_door_usd
     FROM pricing_snapshots
     WHERE sailing_id = $1
     ORDER BY captured_at DESC`,
    [sailingId]
  );

  const currentPricing: Record<string, number> = {};
  for (const p of pricingResult.rows) {
    if (!(p.cabin_type in currentPricing)) {
      currentPricing[p.cabin_type] = parseFloat(p.total_out_the_door_usd);
    }
  }

  // Fetch pricing history (last 20 snapshots for Inside cabin)
  const historyResult = await pool.query(
    `SELECT cabin_type, total_out_the_door_usd, captured_at
     FROM pricing_snapshots
     WHERE sailing_id = $1 AND cabin_type = 'Inside'
     ORDER BY captured_at ASC
     LIMIT 20`,
    [sailingId]
  );

  const priceHistory = historyResult.rows.map((r: any) => ({
    cabinType: r.cabin_type,
    price: parseFloat(r.total_out_the_door_usd),
    date: r.captured_at,
  })) || [];

  // Fetch ship details (if available)
  let shipDetails: SailingContext['shipDetails'] = undefined;
  try {
    const shipResult = await pool.query(
      `SELECT year_built, passenger_capacity, tonnage
       FROM ship_details WHERE ship_name = $1 LIMIT 1`,
      [s.ship_name]
    );
    console.log('[BUILD_CONTEXT] Ship query done');
    if (shipResult.rows.length > 0) {
      const sd = shipResult.rows[0];
      shipDetails = {
        yearBuilt: sd.year_built,
        passengerCapacity: sd.passenger_capacity,
        tonnage: sd.tonnage,
      };
    }
  } catch { /* ship_details may not exist yet */ }

  // Fetch destination insight (if available)
  let destinationInsight: SailingContext['destinationInsight'] = undefined;
  try {
    const destResult = await pool.query(
      `SELECT avg_price_ppd, best_value_months, peak_season_months, price_trend
       FROM destination_insights WHERE destination_region = $1 LIMIT 1`,
      [s.destination_region]
    );
    console.log('[BUILD_CONTEXT] Destination query done');
    if (destResult.rows.length > 0) {
      const di = destResult.rows[0];
      destinationInsight = {
        avgPricePpd: di.avg_price_ppd,
        bestValueMonths: typeof di.best_value_months === 'string' ? JSON.parse(di.best_value_months) : di.best_value_months,
        peakSeasonMonths: typeof di.peak_season_months === 'string' ? JSON.parse(di.peak_season_months) : di.peak_season_months,
        priceTrend: di.price_trend,
      };
    }
  } catch { /* destination_insights may not exist yet */ }

  // Fetch market comparison (if available)
  let marketComparison: SailingContext['marketComparison'] = undefined;
  try {
    const mktResult = await pool.query(
      `SELECT avg_price_ppd, overall_rating, best_value_rating
       FROM market_comparisons WHERE cruise_line = $1 LIMIT 1`,
      [s.cruise_line]
    );
    console.log('[BUILD_CONTEXT] Market query done');
    if (mktResult.rows.length > 0) {
      const mc = mktResult.rows[0];
      marketComparison = {
        avgPricePpd: mc.avg_price_ppd,
        overallRating: mc.overall_rating,
        bestValueRating: mc.best_value_rating,
      };
    }
  } catch { /* market_comparisons may not exist yet */ }

  return {
    sailingId: s.id,
    cruiseLine: s.cruise_line,
    shipName: s.ship_name,
    durationDays: s.duration_days,
    departurePort: s.departure_port,
    destinationRegion: s.destination_region,
    departureDate: s.departure_date,
    itinerary: s.itinerary,
    cabinCategories: s.cabin_categories,
    bookingUrl: s.booking_url,
    currentPricing,
    priceHistory,
    shipDetails,
    destinationInsight,
    marketComparison,
    tripType: preferences?.tripType,
    cabinPriorities: preferences?.cabinPriorities,
  };
}


  async function findCompetingSailings(sailingId: number): Promise<CompetingSailingData[]> {
  const pool = getPool();
  console.log('[FIND_COMP] Starting for sailing', sailingId);
  
  // Get current sailing's route and date
  const currentResult = await pool.query(
    `SELECT destination_region, departure_date, duration_days, cruise_line, ship_name
     FROM sailings WHERE id = $1`,
    [sailingId]
  );
  console.log('[FIND_COMP] Current sailing fetched');
  if (currentResult.rows.length === 0) return [];

  const current = currentResult.rows[0];

  // Find other sailings on same route, similar dates (±14 days), different ship
  const compDate = new Date(current.departure_date).toISOString().split('T')[0];
  const compResult = await pool.query(
    `SELECT s.id AS sailing_id, s.cruise_line, s.ship_name, s.departure_date,
            MIN(ps.total_out_the_door_usd) AS balcony_price
     FROM sailings s
     INNER JOIN pricing_snapshots ps ON ps.sailing_id = s.id AND ps.cabin_type = 'Balcony'
     WHERE s.destination_region = $1
       AND s.id != $2
       AND s.sync_status = 'active'
       AND (s.departure_date::date - $3::date) BETWEEN -14 AND 14
     GROUP BY s.id, s.cruise_line, s.ship_name, s.departure_date
     ORDER BY ABS(s.departure_date::date - $3::date) ASC
     LIMIT 5`,
    [current.destination_region, sailingId, compDate]
  );

  console.log('[FIND_COMP] Competitors found:', compResult.rows.length);
  // Fetch current sailing's balcony price for delta calculation
  const currentBalconyResult = await pool.query(
    `SELECT MIN(ps.total_out_the_door_usd) AS balcony_price
     FROM pricing_snapshots ps
     WHERE ps.sailing_id = $1 AND ps.cabin_type = 'Balcony'`,
    [sailingId]
  );
  const currentBalconyPrice = currentBalconyResult.rows.length > 0
    ? parseFloat(currentBalconyResult.rows[0].balcony_price) : null;

  return compResult.rows.map((r: any) => ({
    sailingId: r.sailing_id,
    cruiseLine: r.cruise_line,
    shipName: r.ship_name,
    departureDate: r.departure_date,
    balconyPrice: parseFloat(r.balcony_price),
    priceDifference: currentBalconyPrice ? Math.round(parseFloat(r.balcony_price) - currentBalconyPrice) : 0,
  }));
}

/* ====================================================================== */
/*  ROUTES                                                                 */
/* ====================================================================== */

/**
 * GET /api/enhanced/deal-analysis/:sailingId
 * Returns the enhanced deal analysis for a specific sailing.
 * Uses cached data if available, otherwise generates on-demand.
 */
router.get('/deal-analysis/:sailingId', async (req: Request, res: Response) => {
  try {
    const sailingId = parseInt(req.params.sailingId, 10);
    if (isNaN(sailingId)) {
      return res.status(400).json({ success: false, error: 'Invalid sailing ID' });
    }

    // Check in-memory cache
    if (req.query.forceRefresh !== 'true') {
      const cached = getCached(dealCache, sailingId);
      if (cached) {
        return res.json({
          success: true,
          data: cached,
          generatedAt: new Date().toISOString(),
          cached: true,
        });
      }
    }

    const context = await buildSailingContext(sailingId);
    if (!context) {
      return res.status(404).json({ success: false, error: 'Sailing not found' });
    }

    const forceRefresh = req.query.forceRefresh === 'true';
    const result = await generateEnhancedDealAnalysis(context, forceRefresh);
    const sanitized = sanitizeDealAnalysisObject(result as unknown as Record<string, unknown>) as unknown as typeof result;
    
    // Store in cache
    if (req.query.forceRefresh !== 'true') {
      setCached(dealCache, sailingId, sanitized);
    }
    
    return res.json({
      success: true,
      data: sanitized,
      generatedAt: new Date().toISOString(),
      cached: false,
    });
  } catch (err: any) {
    console.error('[ENHANCED] Deal analysis route error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

/**
 * POST /api/enhanced/regenerate-deal-analysis/:sailingId
 * Force-refresh the enhanced deal analysis for a single sailing (admin).
 */
router.post('/regenerate-deal-analysis/:sailingId', async (req: Request, res: Response) => {
  try {
    const sailingId = parseInt(req.params.sailingId, 10);
    if (isNaN(sailingId)) {
      return res.status(400).json({ success: false, error: 'Invalid sailing ID' });
    }

    const context = await buildSailingContext(sailingId);
    if (!context) {
      return res.status(404).json({ success: false, error: 'Sailing not found' });
    }

    const result = await generateEnhancedDealAnalysis(context, true);

    return res.json({
      success: true,
      data: result,
      generatedAt: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error('[ENHANCED] Regenerate deal analysis error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

/**
 * GET /api/enhanced/price-forecast/:sailingId
 * Returns the enhanced price forecast for a specific sailing.
 */
router.get('/price-forecast/:sailingId', async (req: Request, res: Response) => {
  try {
    const sailingId = parseInt(req.params.sailingId, 10);
    if (isNaN(sailingId)) {
      return res.status(400).json({ success: false, error: 'Invalid sailing ID' });
    }

    // Check in-memory cache
    if (req.query.forceRefresh !== 'true') {
      const cached = getCached(forecastCache, sailingId);
      if (cached) {
        return res.json({
          success: true,
          data: cached,
          generatedAt: new Date().toISOString(),
          cached: true,
        });
      }
    }

    const context = await buildSailingContext(sailingId);
    if (!context) {
      return res.status(404).json({ success: false, error: 'Sailing not found' });
    }

    const forceRefresh = req.query.forceRefresh === 'true';
    const competitors = await findCompetingSailings(sailingId);
    const result = await generateEnhancedPriceForecast(context, competitors, forceRefresh);
    const sanitized = sanitizeDealAnalysisObject(result as unknown as Record<string, unknown>) as unknown as typeof result;

    // Store in cache
    if (req.query.forceRefresh !== 'true') {
      setCached(forecastCache, sailingId, sanitized);
    }

    return res.json({
      success: true,
      data: sanitized,
      generatedAt: new Date().toISOString(),
      cached: false,
    });
  } catch (err: any) {
    console.error('[ENHANCED] Price forecast route error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

/**
 * POST /api/enhanced/regenerate-forecast/:sailingId
 * Force-refresh the enhanced price forecast for a single sailing (admin).
 */
router.post('/regenerate-forecast/:sailingId', async (req: Request, res: Response) => {
  try {
    const sailingId = parseInt(req.params.sailingId, 10);
    if (isNaN(sailingId)) {
      return res.status(400).json({ success: false, error: 'Invalid sailing ID' });
    }

    const context = await buildSailingContext(sailingId);
    if (!context) {
      return res.status(404).json({ success: false, error: 'Sailing not found' });
    }

    const competitors = await findCompetingSailings(sailingId);
    const result = await generateEnhancedPriceForecast(context, competitors, true);

    return res.json({
      success: true,
      data: result,
      generatedAt: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error('[ENHANCED] Regenerate forecast error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

/**
 * GET /api/enhanced/stats
 * Returns statistics about enhanced analytics coverage.
 */
router.get('/stats', async (_req: Request, res: Response) => {
  try {
    const pool = getPool();

    const dealResult = await pool.query(
      `SELECT COUNT(*) AS count FROM sailings WHERE deal_analysis IS NOT NULL`
    );
    const forecastResult = await pool.query(
      `SELECT COUNT(*) AS count FROM sailings WHERE price_forecast IS NOT NULL`
    );
    const totalResult = await pool.query(
      `SELECT COUNT(*) AS count FROM sailings WHERE sync_status = 'active'`
    );

    return res.json({
      success: true,
      data: {
        enhancedDealAnalyses: parseInt(dealResult.rows[0].count, 10),
        enhancedPriceForecasts: parseInt(forecastResult.rows[0].count, 10),
        totalActiveSailings: parseInt(totalResult.rows[0].count, 10),
      },
    });
  } catch (err: any) {
    console.error('[ENHANCED] Stats error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

/**
 * POST /api/enhanced/batch-analyze
 * Batch-regenerate enhanced deal analyses (admin).
 * Query params: cruiseLine (optional), limit (default 10)
 */
router.post('/batch-analyze', async (req: Request, res: Response) => {
  try {
    const { cruiseLine, limit = 10 } = req.body;
    const parsedLimit = Math.min(50, Math.max(1, parseInt(limit as string, 10) || 10));

    const pool = getPool();
    let query = `SELECT id, cruise_line, ship_name, duration_days, departure_port,
                        destination_region, departure_date, itinerary, cabin_categories, booking_url
                 FROM sailings WHERE sync_status = 'active'`;
    const params: any[] = [];
    let paramIndex = 1;

    if (cruiseLine) {
      query += ` AND cruise_line = $${paramIndex}`;
      params.push(cruiseLine);
      paramIndex++;
    }

    query += ` ORDER BY id LIMIT $${paramIndex}`;
    params.push(parsedLimit);

    const result = await pool.query(query, params);

    // Build contexts and process
    const contexts: SailingContext[] = [];
    for (const s of result.rows) {
      const pricingSnap = await pool.query(
        `SELECT cabin_type, total_out_the_door_usd FROM pricing_snapshots WHERE sailing_id = $1 ORDER BY captured_at DESC`,
        [s.id]
      );
      const currentPricing: Record<string, number> = {};
      for (const p of pricingSnap.rows) {
        if (!(p.cabin_type in currentPricing)) {
          currentPricing[p.cabin_type] = parseFloat(p.total_out_the_door_usd);
        }
      }

      contexts.push({
        sailingId: s.id,
        cruiseLine: s.cruise_line,
        shipName: s.ship_name,
        durationDays: s.duration_days,
        departurePort: s.departure_port,
        destinationRegion: s.destination_region,
        departureDate: s.departure_date,
        itinerary: s.itinerary,
        cabinCategories: s.cabin_categories,
        bookingUrl: s.booking_url,
        currentPricing,
        priceHistory: [],
      });
    }

    const msg = await batchGenerateEnhancedDealAnalyses(contexts, true);
    return res.json({ success: true, data: msg });
  } catch (err: any) {
    console.error('[ENHANCED] Batch analyze error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});


/**
 * POST /api/enhanced/regenerate-all
 * Scans all active sailings for stale/degraded deal analysis and regenerates them.
 * Body: { limit: number } default 20, max 50
 * Returns: count of fixed entries and list of IDs that were regenerated.
 */
router.post('/regenerate-all', async (req: Request, res: Response) => {
  try {
    const limit = Math.min(50, Math.max(1, parseInt(req.body.limit as string, 10) || 20));
    const pool = getPool();

    // Find sailings with deal_analysis that contain placeholder patterns
    const placeholderPatterns = [
      'analysis parsing failed',
      'data unavailable',
      'contact agent for details',
      'manual review recommended',
    ];

    // Build ILIKE conditions for each pattern
    const conditions = placeholderPatterns.map((p, i) =>
      `(deal_analysis::text ILIKE '%${p}%' OR (deal_analysis::json->>'pricingDeepDive')::text LIKE '%${p}%')`
    );
    conditions.push(`LENGTH(deal_analysis::json->>'pricingDeepDive'::text) < 30`);

    const whereClause = conditions.join(' OR ');
    const query = `SELECT id, cruise_line, ship_name FROM sailings WHERE deal_analysis IS NOT NULL AND (${whereClause}) ORDER BY id LIMIT $1`;

    const result = await pool.query(query, [limit]);

    let fixedCount = 0;
    const fixedIds: number[] = [];

    for (const row of result.rows) {
      try {
        const sailingId = row.id;
        const context = await buildSailingContext(sailingId);
        if (!context) {
          console.log(`[REGENERATE] Skipping ${sailingId}: context build failed`);
          continue;
        }
        await generateEnhancedDealAnalysis(context, true);
        fixedIds.push(sailingId);
        fixedCount++;
        console.log(`[REGENERATE] Fixed sailing ${sailingId} (${row.cruise_line} - ${row.ship_name})`);
      } catch (err: any) {
        console.error(`[REGENERATE] Failed to fix sailing ${row.id}: ${err.message}`);
      }
    }

    return res.json({
      success: true,
      data: {
        fixed: fixedCount,
        totalFound: result.rows.length,
        sailingIds: fixedIds,
      },
    });
  } catch (err: any) {
    console.error('[REGENERATE] Error:', err.message);
    res.status(500).json({ success: false, error: err.message });
  }
});

export default router;
